{
 "title": "Alluxio-Edge-Trino-Cache-Monitor",
 "time": { "from": "2023-12-13T16:50:14.018Z", "to": "2023-12-13T16:58:49.876Z" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alluxio Edge - Cache Hit Rate",
   "type": "timeseries",
   "description": "Client.CacheHitRate: Cache hit rate: (# bytes read from cache) / (# bytes requested).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) ({job=\"trino worker\", __name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesReadCache.*_OneMinuteRate\"}) / \n(sum by (instance) ({job=\"trino worker\", __name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesReadCache.*_OneMinuteRate\"}) + \n sum by (instance) ({job=\"trino worker\", __name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesRequestedExternal.*_OneMinuteRate\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Evictions (pages, bytes, errors)",
   "type": "timeseries",
   "description": "Client.CachePagesEvicted: Total number of pages evicted from the client cache.\n\nClient.CacheBytesEvicted: Total number of bytes evicted from the client cache.\n\nClient.CachePutEvictionErrors: Number of failures when putting cached data in the client cache due to failed eviction.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePagesEvicted.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesEvicted.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutEvictionErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Data Read from Cache (Cache Hits)",
   "type": "timeseries",
   "description": "Client.CacheBytesReadCache: Total number of bytes read from the client cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesReadCache.*_OneMinuteRate\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Data Read from UFS (Cache Misses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesRequestedExternal.*_OneMinuteRate\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Space Used ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheSpaceUsed.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Effectiveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Alluxio Edge - Individual error counts by error type",
   "type": "timeseries",
   "description": "Client.CachePutInsufficientSpaceErrors: Number of failures when putting cached data in the client cache due to insufficient space made after eviction.\n\nClient.CachePutNotReadyErrors: Number of failures when cache is not ready to add pages.\n\nClient.CachePutBenignRacingErrors: Number of failures when adding pages due to racing eviction. This error is benign.\n\nClient.CachePutStoreWriteErrors: Number of failures when putting cached data in the client cache due to failed writes to page store.\n\nClient.CachePutEvictionErrors: Number of failures when putting cached data in the client cache due to failed eviction.\n\nClient.CachePutStoreDeleteErrors: Number of failures when putting cached data in the client cache due to failed deletes in page store.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutInsufficientSpaceErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutNotReadyErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutBenignRacingErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutStoreWriteErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutEvictionErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutStoreDeleteErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Total Put Error Count",
   "type": "timeseries",
   "description": "Client.CachePutErrors: Number of failures when putting cached data in the client cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Individual Error Counts by Error Type",
   "type": "timeseries",
   "description": "Client.CacheGetNotReadyErrors: Number of failures when cache is not ready to get pages.\n\nClient.CacheGetStoreReadErrors: Number of failures when getting cached data in the client cache due to failed read from page stores.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheGetNotReadyErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheGetStoreReadErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Total Get Error Count",
   "type": "timeseries",
   "description": "Client.CacheGetErrors: Number of failures when getting cached data in the client cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheGetErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Page Read External Time Nanos ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePageReadExternalTimeNanos.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Deletion Error",
   "type": "timeseries",
   "description": "Client.CacheDeleteNonExistingPageErrors: Number of failures when deleting pages due to absence.\n\nClient.CacheDeleteNotReadyErrors: Number of failures when cache is not ready to delete pages.\n\nClient.CacheDeleteFromStoreErrors: Number of failures when deleting pages from page stores.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheDeleteNonExistingPageErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheDeleteNotReadyErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheDeleteFromStoreErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Read External ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesExternal.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Data Evicted ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesEvicted.*OneMinuteRate\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Page Read Cache Time Nanos ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePageReadCacheTimeNanos.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Alluxio Edge - All Heap Usage",
   "type": "timeseries",
   "description": "heap.used: The amount of memory from heap area that has been used.\n\nheap.usage: The amount of memory from heap area currently used in GB.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_heap_used.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_heap_usage.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}