{
 "title": "Alluxio Edge Dashboard v1.0",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alluxio Edge - Ready Coordinator and Workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor({__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheState_Count\"})) / 2",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Space Used",
   "type": "stat",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheSpaceUsed_Value\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cached Space Available",
   "type": "stat",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheSpaceAvailable.*_Value\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$C / ( $C + $U )", "type": "math" }
   ]
  },
  {
   "title": "Alluxio Edge - Cache Evictions (pages, bytes, errors)",
   "type": "timeseries",
   "description": "Total number of pages evicted from the Alluxio Edge cache\n\nClient.CacheBytesEvicted: Total number of bytes evicted from the client cache.\n\nClient.CachePutEvictionErrors: Number of failures when putting cached data in the client cache due to failed eviction.",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePagesEvicted.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesEvicted.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CachePutEvictionErrors.*\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Data Read from Cache (Cache Hits)",
   "type": "timeseries",
   "description": "Client.CacheBytesReadCache: Total number of bytes read from the client cache.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesReadCache.*_OneMinuteRate\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Data Read from UFS (Cache Misses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheBytesRequestedExternal.*_OneMinuteRate\", job=\"trino worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cost Saving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "AWS S3 API Cost - Without Alluxio Edge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A + $G) / 1000 * 0.0004 ", "type": "math" }
   ]
  },
  {
   "title": "AWS S3 API Cost - With Alluxio Edge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($G) / 1000 * 0.0004 ", "type": "math" }
   ]
  },
  {
   "title": "AWS S3 API Cost Saving With Alluxio Edge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A) / 1000 * 0.0004 ", "type": "math" }
   ]
  },
  {
   "title": "Alluxio Edge - Data Cache Hit Rate (Per 15 Second Period)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheHitRequests_Count\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Alluxio Edge - Cache Space Used Per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheSpaceUsed.*_Value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cached Space Available Per worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheSpaceAvailable.*_Value\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alluxio Edge - Cached Pages Per Worker",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "alluxio_shaded_client_org_alluxio_Client_CachePages_Number",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cache Get Error Total Rate",
   "type": "timeseries",
   "description": "Total number of pages in the client cache",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(app) (increase({__name__=~\"alluxio_shaded_client_org_alluxio_Client_CacheGetErrors_Count\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "alluxio_shaded_client_org_alluxio_os_cpuLoad_Number",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "OS Max File Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "alluxio_shaded_client_org_alluxio_os_maxFileCount_Value",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "OS Open File Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "alluxio_shaded_client_org_alluxio_os_openFileCount_Number",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Young GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(java_lang_G1_Young_Generation_CollectionCount[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Young GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 66 },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old GC Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "increase(alluxio_shaded_client_org_alluxio_G1_Old_Generation_time_Value[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old GC Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(alluxio_shaded_client_org_alluxio_G1_Old_Generation_time_Value[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}