version: '3.7' 

services:

  trino-coordinator:
    image: mytrino/trino-alluxio-edge
    hostname: trino-coordinator
    container_name: trino-coordinator
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
    networks:
      custom:
        ipv4_address: 172.26.0.10
    volumes:
      - trino-coordinator-data:/data
    expose:
      - 8080
    ports:
      - '8080:8080'
    command:
      - /bin/bash
      - -c 
      - |
        sed -i "s/coordinator=false/coordinator=true/" /etc/trino/config.properties
        sed -i "s/node-scheduler.include-coordinator=true/node-scheduler.include-coordinator=false/" /etc/trino/config.properties
        /usr/lib/trino/bin/run-trino

  trino-worker1:
    image: mytrino/trino-alluxio-edge
    hostname: trino-worker1
    container_name: trino-worker1
    shm_size: '1.5gb'
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G
    networks:
      custom:
        ipv4_address: 172.26.0.11
    volumes:
      - trino-worker1-data:/data
    expose:
      - 8080
    command:
      - /bin/bash
      - -c 
      - |
        sed -i "s/coordinator=true/coordinator=false/" /etc/trino/config.properties
        sed -i "s/node-scheduler.include-coordinator=true/node-scheduler.include-coordinator=false/" /etc/trino/config.properties
        echo "discovery.uri=http://trino-coordinator:8080" >> /etc/trino/config.properties
        /usr/lib/trino/bin/run-trino

  mariadb:
    image: 'mariadb:10.4'
    hostname: mariadb
    container_name: mariadb
    networks:
      custom:
        ipv4_address: 172.26.0.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    volumes:
      - mariadb-data:/var/lib/mysql

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    container_name: hive-metastore
    networks:
      custom:
        ipv4_address: 172.26.0.4
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./config-files:/tmp/config-files:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
      - minio
    entrypoint: >
      /bin/sh -c "
        cp /tmp/config-files/hive/metastore-site.xml /opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml
        /entrypoint.sh
        "
  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    networks:
      custom:
        ipv4_address: 172.26.0.5
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  minio-create-buckets:
    image: minio/mc:latest
    container_name: minio-create-buckets
    networks:
      custom:
        ipv4_address: 172.26.0.6
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      if [ \"`/usr/bin/mc ls myminio`\" == \"\" ]; then 
         echo \"Creating bucket myminio/hive\" && \
         /usr/bin/mc mb myminio/hive && \
         /usr/bin/mc policy download myminio/hive && \
         /usr/bin/mc cp /etc/motd myminio/hive/warehouse/.temp_file; 
      else 
         echo \"Bucket myminio/hive already exists, skipping create\"; 
      fi;
      exit 0
      "
  prometheus:
    image: prom/prometheus:v2.22.2
    container_name: prometheus
    hostname: prometheus
    domainname: docker.com
    networks:
      custom:
        ipv4_address: 172.26.0.8
    expose:
      - 9090
    ports:
      - 9090:9090
    volumes:
      - ./config-files/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle --log.level=debug --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana-oss:10.0.4
    networks:
      custom:
        ipv4_address: 172.26.0.9
    container_name: grafana
    hostname: grafana
    domainname: docker.com
    ports:
      - 3000:3000
    volumes:
      - ./config-files:/tmp/config-files:ro
      - ./bootstrap/bootstrap-grafana.sh:/bootstrap.sh
    user: root
    entrypoint: ["/bootstrap.sh"]

volumes:
  mariadb-data:
    driver: local
  minio-data:
    driver: local
  trino-coordinator-data:
    driver: local
  trino-worker1-data:
    driver: local
  prometheus_data:
    driver: local

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/16
        gateway: 172.26.0.1
