#
# FILE: jmx_export_config.yaml
#
# DESC: This is the Alluxio Edge Java JMX metrics export file. It should
#       be placed in: /etc/trino/jmx_export_config.yaml
#
---
startDelaySeconds: 0
ssl: false
global:
  scrape_interval:     15s
  evaluation_interval: 15s
rules:
- pattern: ".*"
